### ISSUE TITLE
Modify runtime programs to send all circuit jobs via circuit-runner

### ISSUE THREAD

**Issue by renier** [Qiskit-Partners/qiskit-runtime#54]
It is possible to now send larger circuits via the circuit-runner. That means it should no be necessary to go outside of the runtime to send Qobj jobs.

cc: @jyu00

**Comment by nonhermitian** [comment]
We might want to pin down the results issue first though.

**Comment by jyu00** [comment]
@nonhermitian what results issue?

**Comment by nonhermitian** [comment]
We can send huge jobs but there is an issue with results not coming back in some cases of multiple circuits in a job. Even when the result data is small:

File "/opt/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
JSONDecodeError: Expecting value

**Comment by renier** [comment]
@nonhermitian agreed. let's meet next week to try to reproduce that. unless Jessie beats me to it.

**Comment by renier** [comment]
FYI, this is in production since XP was already better than before.

**Comment by nonhermitian** [comment]
Does this mean every program needs to create another docker to run circuits?

**Comment by jyu00** [comment]
@nonhermitian technically _no_ Qiskit Runtime program will be using `circuit-runner`, since we don't have inter-program communication (yet). What @renier was referring to was that in the QKA tutorial, we use the QKA program to train the kernel. After we get the results back we want to test the new kernel, and we submits circuits to do so. Right now these circuits are submitted as a regular circuit job (i.e. using `backend.run()`) because of the input size issue. We can now submit them to `circuit-runner`.

**Comment by nonhermitian** [comment]
Ahh ok, so that is outside of the QKA program itself then.

There are advantages to having everything go through the circuit runner program though.  For example, if the VQE program could call the circuit runner, then it would be quite easy to integrate things like mitigation or computed expectation values into the code.  i.e. the circuit runner would be the default functionality of a circuit execution on the targeted backend.

**Comment by nonhermitian** [comment]
Just to close on the above, the issue with null results was due to limitations in the staging simulator instances.  The circuit runner appears to be fine.

**Comment by jyu00** [comment]
> There are advantages to having everything go through the circuit runner program though.

Yeah we've had a few requests about this. It'd allow us to turn some programs into microservices. But it'll take some architectural change so will take a bit longer.

**Comment by jyu00** [comment]
Closing as this is discussed somewhere else.
