### ISSUE TITLE
VQEProgram does not converge to the expected value

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit-Partners/qiskit-runtime#59]
I tried running VQE runtime jobs on simulator following the [VQE runtime tutorial](https://qiskit.org/documentation/partners/qiskit_runtime/tutorials/vqe.html). The results look rather weird; the energy didn't converge to the expected value.

Result from local VQE
![vqe-local](https://user-images.githubusercontent.com/7631333/128736543-cea3e24e-039f-454a-87ac-c8b28cea6b76.png)

Result from VQE runtime job on simulator
![vqe-runtime](https://user-images.githubusercontent.com/7631333/128736553-bdf66101-756d-4eee-bdb6-888be3a9dc24.png)

**Comment by HuangJunye** [comment]
I am not sure if this is the right repo to report this issue. Is qiskit-nature repo a better place for this issue?

**Comment by HuangJunye** [comment]
I verified that this issue persist for Qiskit 0.28 and 0.29.

**Comment by Cryoris** [comment]
Thanks for reporting this! It's fixed now and the optimizer converges correctly: 
![image](https://user-images.githubusercontent.com/5978796/129153449-746fb765-e0bd-4251-a4e7-f6eb06aa1cc8.png)

For those interested: the issue was that the batch-optimized optimizers did not get passed into VQE correctly, which was not a problem if the optimizer was passed as object but didn't work if the optimizer was passed as dict.

**Comment by HuangJunye** [comment]
That’s great! Thanks a lot for fixing this.
